version: '3.8'
services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment:
            - NEW_SECRET_KEY=!od%n7e-fv=zrc7o$$@d2u2-+k2%+h&b@ejhkq1_bd!cdl@_t1m
            - DEBUG=1
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:11
        environment: 
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:        